<a href="https://colab.research.google.com/github/techySPHINX/Python_Libraries_Learning/blob/main/numpy_starting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
ls =[1,2,3,4,5]
array = np.array(ls)
print(type(array))
print(array.shape)
print(array.ndim)

<class 'numpy.ndarray'>
(5,)
1


In [13]:
array = np.arange(5)
array


array([0, 1, 2, 3, 4])

In [12]:
arr = np.arange(0,10,2,dtype='float')
arr

array([0., 2., 4., 6., 8.])

In [15]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
import numpy as np

ls = [[1,2,3],[4,5,6]]
arr1 = np.array(ls)
arr1.shape

ls1 = [[1,2],[3,4],[5,6]]
arr2 = np.array(ls1)
arr2.shape

np.dot(arr1,arr2)

array([[22, 28],
       [49, 64]])

In [1]:
import numpy as np

arr1 = np.arange(10).reshape(2, 5)  # 2D array
arr2 = np.arange(5)  # 1D array

# Element-wise addition using broadcasting
result = arr1 + arr2

print(result)


[[ 0  2  4  6  8]
 [ 5  7  9 11 13]]


In [2]:
import numpy as np
#fancy indexing
data = np.arange(12).reshape(3, 4)
indices = np.array([1, 0, 2])

selected_data = data[indices]

print(selected_data)


[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


In [3]:
data = np.array([1, 4, 2, 5, 3])
condition = data % 2 == 0  # Boolean mask (even numbers)

# Filter elements using boolean mask
even_numbers = data[condition]

print(even_numbers)


[4 2]


In [4]:
import numpy as np

data_int32 = np.random.randint(1, 256, size=1000000, dtype=np.int32)
data_uint8 = data_int32.astype(np.uint8)  # Conversion

print(f"Memory usage with int32: {data_int32.nbytes / (1024 * 1024):.2f} MB")
print(f"Memory usage with uint8: {data_uint8.nbytes / (1024 * 1024):.2f} MB")


Memory usage with int32: 3.81 MB
Memory usage with uint8: 0.95 MB


In [5]:
# Original array
original_data = np.arange(10)

# View (shares memory with original)
data_view = original_data.view()

# Modifications on the view affect the original
data_view[:] = 2 * original_data

print(f"Original data after view modification: {original_data}")

# Copy (creates a new array)
data_copy = original_data.copy()

# Modifications on the copy don't affect the original
data_copy[:] = 3 * original_data

print(f"Original data after copy modification: {original_data}")


Original data after view modification: [ 0  2  4  6  8 10 12 14 16 18]
Original data after copy modification: [ 0  2  4  6  8 10 12 14 16 18]


In [6]:
large_array = np.random.rand(10000)

# Using `where` for lazy evaluation
condition = large_array > 0.5
filtered_data = large_array[condition]  # Computation happens here
#lazy evaluation
print(f"Shape of filtered data (lazy evaluation): {filtered_data.shape}")

filtered_data_loop = []
for value in large_array:
    if value > 0.5:
        filtered_data_loop.append(value)

filtered_data_loop = np.array(filtered_data_loop)
print(f"Shape of filtered data (explicit loop): {filtered_data_loop.shape}")


Shape of filtered data (lazy evaluation): (5013,)
Shape of filtered data (explicit loop): (5013,)


In [1]:
import numpy as np
data = np.random.randint(1, 100, size=10)

cond1 = data > 50
cond2 = data % 3 == 0

combined_condition = np.logical_and(cond1, cond2)
filtered_data = data[combined_condition]

dcombined_condition = np.logical_or(cond1,cond2)
filteredd_data = data[dcombined_condition]

print("Original data:", data)
print("Filtered data (elements > 50 and divisible by 3):", filtered_data)
print("Filtered data (elements > 50 or divisible by 3):", filteredd_data)


Original data: [99 53 92 59 63 16 60  2 97  4]
Filtered data (elements > 50 and divisible by 3): [99 63 60]
Filtered data (elements > 50 or divisible by 3): [99 53 92 59 63 60 97]


In [8]:
import numpy as np
from numpy.linalg import inv

A = np.array([[2, 1], [1, 3]])
# Solve linear system Ax = b for x (x = inv(A) * b)
b = np.array([5, 1])
x = inv(A) @ b

print("Solution (x):", x)


Solution (x): [ 2.8 -0.6]
